name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7
      - name: Passo 1
        run: echo "Construir a imagem da aplicação"
      - name: Passo 2
        run: echo "Publicar a imagem no Docker Hub"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 1
        run: echo "Deploy da aplicação"
        
