name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Login no Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da imagem Docker e envio para o Docker Hub
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            marcelodpbarbieri/review-filmes:v${{ github.run_number }}
            marcelodpbarbieri/review-filmes:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Configuração das Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configuração do KubeConfig
        run: aws eks update-kubeconfig --name clusterLab
        
      - name: Deploy da Aplicação
        uses: Azure/k8s-deploy@v5.0.0
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            marcelodpbarbieri/review-filmes:v${{ github.run_number }}
          